# Run the RISC-V riscv-arch-test test framework to check compatibility with ISA specs.

name: 'riscv-arch-test'

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
        - I
        - C
        - M
        - privilege
        - Zifencei
    name: 'RISC-V Compatibility Check'

    steps:

      - name: '🧰 Repository Checkout'
        uses: actions/checkout@v2

      - name: '🚧 Run RISC-V Architecture Tests'
        uses: docker://ghcr.io/stnolting/neorv32/sim
